default_language_version:
  python: python3
exclude: |
  (?x)^(
      d3rlpy_data/|
      d3rlpy_logs/|
      docs/|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: [ --profile, black ]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/pylint
    rev: v2.9.6
    hooks:
      - id: pylint
        args: [ "--rcfile=.pylintrc" ]
