name: Build

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up docker image
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: >-
        python -m
        pip install
        -r requirements.txt
        --user
    - name: Install pytest
      run: >-
        python -m
        pip install
        pytest
        --user
    - name: Run tests
      run: >-
        python -m pytest tests/

  build-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up docker image
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install build tools
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build wheel
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
